import { StandardizedProduct } from './types';

export const STANDARDIZED_LIST: StandardizedProduct[] = [
  { id: '45419', name: 'NOREPINEFRINA 2MG/ML-4ML AMP EV HIPOLABOR', abc: 'C' },
  { id: '29547', name: 'TARFIC 1MG CAPS GEL-TACROLIMO', abc: 'C' },
  { id: '43709', name: '(O)GLUCONATO CALCIO 100MG/ML(10%)-10ML AMP IV HIPOLABOR', abc: 'C' },
  { id: '2352', name: '(O)SOLU MEDROL 125MG FR/AMP IM/IV-METILPREDNISOLONA SUC SOD', abc: 'C' },
  { id: '44189', name: 'CEFEPIMA 1.000MG FR/AMP EV NOVAFARMA', abc: 'C' },
  { id: '44415', name: '(O)LORAZEPAM 2MG COMP MEDLEY', abc: 'C' },
  { id: '44771', name: 'GLUCONATO CALCIO 100MG/ML(10%)-10ML AMP EV(MANIPULADO)', abc: '' },
  { id: '45487', name: 'BETAPROSPAN 5/2MG/ML-1ML AMP IM-BETAMETASONA DIP/FOSF DIS', abc: 'C' },
  { id: '46923', name: 'AZITROMICINA 500MG COMP REV MEDLEY', abc: 'C' },
  { id: '32521', name: 'CAPTOPRIL 12,5MG COMP MEDLEY', abc: 'C' },
  { id: '3002', name: 'DIPRIVAN 1%-100ML FR/AMP EV-PROPOFOL', abc: 'C' },
  { id: '3007', name: 'DIPRIVAN 1%-50ML FR/AMP EV-PROPOFOL', abc: 'C' },
  { id: '11271', name: '(O)UNASYN 2.000/1.000MG FR/AMP IM/IV-AMPICILINA/SULBACTAM', abc: 'C' },
  { id: '713', name: 'ZINNAT 250MG COMP REV-CEFUROXIMA', abc: 'C' },
  { id: '16279', name: 'OPTIRAY 350MG/ML-100ML SER EV-IOVERSOL', abc: 'C' },
  { id: '180', name: 'NOVOSEVEN 50KUI(1MG) AMP EV-ALFAEPTACOGUE ATIVADO', abc: 'C' },
  { id: '3181', name: 'AEROLIN 0,5MG/ML-1ML AMP IM/SC/EV-SALBUTAMOL', abc: 'C' },
  { id: '2905', name: '(O)SORCAL 900MG/G-30G ENV-POLIESTIRENOSSULFONATO CALCIO', abc: 'C' },
  { id: '3280', name: '(O)SUCRAFILM 1G COMP MAST-SUCRALFATO', abc: 'C' },
  { id: '15399', name: 'EMEND 150MG FR/AMP EV-FOSAPREPITANTO DIMEGLUMINA(GELAD)', abc: '' },
  { id: '32420', name: 'CIPROFLOXACINO 2MG/ML-200ML(400MG) BOLSA SF EV HALEX ISTAR', abc: 'C' },
  { id: '32283', name: 'RISPERIDON 1MG COMP REV-RISPERIDONA', abc: 'C' },
  { id: '3671', name: 'TIAMINA(VIT B1)100MG/ML-2ML AMP EV(MANIPULADO)', abc: 'C' },
  { id: '202', name: 'ALPRAZOLAM 0,5MG COMP EMS', abc: 'C' },
  { id: '3064', name: '(O)RAMIPRIL 5MG COMP BIOSINTETICA', abc: 'C' },
  { id: '853', name: 'NIMBIUM 2MG/ML-5ML FR/AMP EV-CISATRACURIO(GELAD)', abc: 'C' },
  { id: '39', name: 'ZOVIRAX 200MG COMP-ACICLOVIR', abc: 'C' },
  { id: '567', name: '(O)NEOCAINA ISOBARICA 0,5%-4ML AMP IV-BUPIVACAINA', abc: 'C' },
  { id: '20017', name: 'CITRATO SODIO 4%(4MG/ML)-3000ML BOLSA SF', abc: 'C' },
  { id: '565', name: '(O)NEOCAINA 0,5%-20ML FR/AMP IV-BUPIVACAINA', abc: 'C' },
  { id: '18269', name: 'ZOMETA 4MG-100ML FR/AMP EV-ACIDO ZOLEDRONICO', abc: '' },
  { id: '603', name: '(O)ROCALTROL 0,25MCG CAPS GEL-CALCITRIOL', abc: 'C' },
  { id: '12186', name: '(O)DRAMIN B6 25/5MG/ML-20ML FR-DIMENIDRINA/PIRIDOXINA', abc: 'C' },
  { id: '1077', name: 'PRADAXA 150MG CAPS-DABIGATRANA', abc: 'C' },
  { id: '3011', name: 'DIPRIVAN PFS 2%-50 ML SER PREEN EV-PROPOFOL', abc: 'C' },
  { id: '1259', name: 'PERSANTIN 10MG-2ML AMP EV-DIPIRIDAMOL', abc: 'C' },
  { id: '142', name: 'AGUA OXIGENADA 10VOL-1000ML FR TOP RIO QUIMICA', abc: 'C' },
  { id: '214', name: 'ACTILYSE 20MG-20ML FR/AMP EV-ALTEPLASE', abc: 'C' },
  { id: '223', name: '(O)AMICACINA 250MG/ML-2ML AMP IM/IV EUROFARMA', abc: 'C' },
  { id: '2355', name: '(O)SOLU MEDROL 500MG FR/AMP IM/IV-METILPREDNISOLONA SUC SOD', abc: 'C' },
  { id: '2824', name: 'DOLANTINA 50MG/ML-2ML AMP IM-PETIDINA', abc: 'C' },
  { id: '2416', name: 'DORMONID 5MG/ML-3ML AMP IM/EV-MIDAZOLAM', abc: 'C' },
  { id: '2569', name: '(O)ANNITA 500MG COMP REV-NITAZOXANIDA', abc: 'C' },
  { id: '2967', name: 'PREDSIM 3MG/ML-100ML FR-PREDNISOLONA FOSF SOD', abc: 'C' },
  { id: '1386', name: 'ESCINA/DIETILAMINA 10/50MG/G-30G BG GEL TOP BIOLAB', abc: 'C' },
  { id: '3215', name: '(O)SEVORANE 250ML FR INAL-SEVOFLURANO', abc: 'C' },
  { id: '3718', name: 'STILNOX CR 12,5MG COMP LIB PROL-ZOLPIDEM', abc: 'C' },
  { id: '12850', name: '(O)XYLOCAINA 10%-50ML FR SPR ORAL-LIDOCAINA', abc: 'C' },
  { id: '12415', name: 'LANEXAT 0,1MG/ML-5ML AMP EV-FLUMAZENIL', abc: 'C' },
  { id: '3036', name: 'QUETIAPINA 100MG COMP REV CRISTALIA', abc: 'C' },
  { id: '2337', name: 'METILDOPA 250MG COMP REV BIOSINTETICA', abc: 'C' },
  { id: '232', name: 'AMINOFILINA 24MG/ML-10ML AMP EV(MANIPULADO)', abc: 'C' },
  { id: '273', name: '(O)AMPICILINA 1G FR/AMP IV/IM AUROBINDO', abc: 'C' },
  { id: '572', name: 'BUPROPIONA 150MG COMP LIB PROL EUROFARMA', abc: 'C' },
  { id: '695', name: 'CEFAZOLINA 1.000MG FR/AMP IM/EV ABL', abc: 'C' },
  { id: '697', name: 'CEFEPIMA 1.000MG FR/AMP EV/IM ABL', abc: 'C' },
  { id: '709', name: 'ROCEFIN 1.000MG FR/AMP IV-CEFTRIAXONA', abc: 'C' },
  { id: '751', name: 'CETOPROFENO 100MG FR/AMP EV EUROFARMA', abc: 'C' },
  { id: '752', name: 'PROFENID 100MG FR/AMP EV-CETOPROFENO', abc: 'C' },
  { id: '1360', name: '(BC)CLEXANE 80MG/0,8ML SER SC-ENOXAPARINA', abc: '' },
  { id: '2020', name: 'OPTIRAY 320MG/ML-100ML FR/AMP EV-IOVERSOL', abc: 'C' },
  { id: '3040', name: 'SEROQUEL 25MG COMP REV-QUETIAPINA', abc: 'C' },
  { id: '1767', name: '(O)GLICERIN-GLICERINA 2,392G SUP RETAL INFANTIL(GELAD)', abc: 'C' },
  { id: '27849', name: 'AMIODARONA 50MG/ML-3ML AMP EV(MANIPULADO)', abc: 'C' },
  { id: '31180', name: '(I)FAZOLON 1.000MG FR/AMP IM/IV-CEFAZOLINA', abc: 'C' },
  { id: '834', name: 'CIPROFLOXACINO 2MG/ML-200ML(400MG) BOLSA SF EV EUROFARMA', abc: 'C' },
  { id: '1402', name: 'UNI HIOSCIN 20MG/ML-1ML AMP EV/IM/SC-ESCOPOLAMINA', abc: 'C' },
  { id: '1515', name: '(O)DUROGESIC D-TRANS 100MCG/H ADES TRANSD TOP-FENTANILA', abc: 'C' },
  { id: '1800', name: '(O)GLICOSE 750MG/ML(75%)-10ML AMP EV ISOFARMA', abc: 'C' },
  { id: '1651', name: 'ARIXTRA 2,5MG/0,5ML SER PREEN SC-FONDAPARINUX', abc: 'C' },
  { id: '2431', name: 'PROSTOKOS 200MCG COMP VAG-MISOPROSTOL', abc: 'C' },
  { id: '3439', name: 'TYGACIL 50MG FR/AMP EV-TIGECICLINA', abc: 'C' },
  { id: '1888', name: '(O)HIDROCORTISONA SUC 100MG FR/AMP IM/EV UNIAO QUIMICA', abc: 'C' },
  { id: '2023', name: 'OPTIRAY 320MG/ML-50ML FR/AMP EV-IOVERSOL', abc: 'C' },
  { id: '2475', name: '(O)AVALOX 1,6MG/ML-250ML BOLSA SF-MOXIFLOXACINO', abc: 'C' },
  { id: '2635', name: '(O)OLEO MINERAL 120ML FR CRISTALIA', abc: 'C' },
  { id: '2686', name: '(O)OXACILINA 500MG FR/AMP IM/IV EUROFARMA', abc: 'C' },
  { id: '2718', name: 'ONICIT 0,05MG/ML-1,5ML FR/AMP EV-PALONOSETRONA', abc: 'C' },
  { id: '2785', name: 'BEXTRA 40MG FR/AMP IM/EV-PARECOXIBE', abc: 'C' },
  { id: '3009', name: 'DIPRIVAN PFS 1%-50ML SER PREEN EV-PROPOFOL', abc: 'C' },
  { id: '3075', name: 'FASTURTEC 1,5MG FR/AMP EV-RASBURICASE(GELAD)', abc: 'C' },
  { id: '3076', name: 'ULTIVA 2MG FR/AMP EV-REMIFENTANILA', abc: '' },
  { id: '3136', name: 'ROPIVACAINA 2MG/ML-20ML AMP EPI EUROFARMA', abc: 'C' },
  { id: '2807', name: '(O)VASCER 20MG/ML-5ML AMP IV-PENTOXIFILINA', abc: 'C' },
  { id: '3258', name: 'DIANEAL PD-2 1,5%-5L BLS SF ITP(SOLUCAO DIALISE PERITONEAL)', abc: 'C' },
  { id: '3133', name: 'NAROPIN 10MG/ML-20ML AMP EPI-ROPIVACAINA', abc: 'C' },
  { id: '1280', name: 'NOVALGINA 500MG COMP-DIPIRONA', abc: 'C' },
  { id: '2596', name: '(O)NOREPINEFRINA 2MG/ML-4ML AMP IV FRESENIUS', abc: 'C' },
  { id: '1585', name: 'ZOLTEC 2MG/ML-100ML BOLSA SF EV-FLUCONAZOL', abc: 'C' },
  { id: '2364', name: '(O)PLASIL 5MG/ML-2ML AMP IM/IV-METOCLOPRAMIDA', abc: 'C' },
  { id: '2015', name: 'OMNIPAQUE 300MG/ML-50ML FR IT-IOEXOL', abc: 'C' },
  { id: '27258', name: 'ANORO ELLIPTA 62,5/25MCG-30DOSES FR C/ INAL-UMECLID/VILANTER', abc: 'C' },
  { id: '16864', name: 'RAPAMUNE 2MG DRG-SIROLIMO', abc: 'C' },
  { id: '28139', name: 'GLICEROFOSFATO SODIO 216MG/ML-20ML FR/AMP EV(MANIPULADO)', abc: 'C' },
  { id: '16695', name: 'NOXAFIL 40MG/ML-105ML FR SUSP ORAL-POSACONAZOL', abc: 'C' },
  { id: '10368', name: 'RINGER SIMPLES 500ML SF PVC BAXTER', abc: 'C' },
  { id: '1672', name: '(O)FOSFATO SOD MONO/DIBASICO 160/60MG-130ML FR RETAL CRISTAL', abc: 'C' },
  { id: '333', name: 'LIPITOR 20MG COMP REV-ATORVASTATINA', abc: 'C' },
  { id: '2241', name: 'LORAX 1MG COMP-LORAZEPAM', abc: 'C' },
  { id: '12840', name: '(O)XYLOCAINA S/VASO 1%-20ML FR/AMP IV-LIDOCAINA', abc: 'C' },
  { id: '16750', name: '(O)AFINITOR 10MG COMP-EVEROLIMO', abc: 'C' },
  { id: '31968', name: 'BROMOPRIDA 5MG/ML-2ML AMP EV/IM HIPOLABOR', abc: 'C' },
  { id: '32020', name: 'BICARBONATO SODIO 84MG/ML(8,4%)-250ML FR EV HYPOFARMA', abc: 'C' },
  { id: '3593', name: 'DOBUTREX 12,5MG/ML-20ML AMP EV-DOBUTAMINA', abc: 'C' },
  { id: '1035', name: '(O)IRUXOL MONO 0,6UI/G-30G BG POM TOP-COLAGENASE', abc: 'C' },
  { id: '2240', name: '(O)LORAZEPAM 1MG COMP EMS', abc: 'C' },
  { id: '2301', name: 'MERONEM 500MG FR/AMP EV-MEROPENEM', abc: 'C' },
  { id: '2591', name: 'TRIDIL 5MG/ML-10ML AMP EV-NITROGLICERINA', abc: 'C' },
  { id: '3294', name: '(O)SULFADIAZINA PRATA 10MG/G-30G BG CREM TOP PRATI', abc: 'C' },
  { id: '32786', name: '(O)GABAPENTINA 300MG CAPS EMS', abc: 'C' },
  { id: '29284', name: '(O)NEURONTIN 300MG CAPS-GABAPENTINA', abc: 'C' },
  { id: '3377', name: 'TARGOCID 400MG FR/AMP EV/IM -TEICOPLANINA', abc: 'C' },
  { id: '3004', name: 'DIPRIVAN 1%-20ML AMP EV-PROPOFOL', abc: 'C' },
  { id: '3643', name: 'VERAPAMIL 80MG COMP REV BIOSINTETICA', abc: 'C' },
  { id: '619', name: 'CAPTOPRIL 12,5MG COMP EMS', abc: 'C' },
  { id: '1354', name: 'CLEXANE 20MG/0,2ML SER SC-ENOXAPARINA', abc: '' },
  { id: '2671', name: 'ZOFRAN 2MG/ML-4ML AMP EV-ONDANSETRONA', abc: 'C' }
];
